# Etapa 1: Construcción
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos de configuración y dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install --force

# Copiar todo el código fuente
COPY . .

# Generar la aplicación Angular en modo producción
RUN npm run build -- --configuration production --base-href /

# Etapa 2: Servir la aplicación
FROM nginx:stable-alpine

# Copiar los archivos del build al servidor Nginx
COPY --from=build /app/dist/front/ /usr/share/nginx/html

# Copiar archivo de configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
